### ISSUE TITLE
Explain why crom is needed

### ISSUE THREAD

**Issue by kgryte** [mbostock/crom#5]
NPM already supports pretty much all use cases stated in the `README`.
* `npm`, the module, is decoupled from NPM, the registry. You are free to point the client to any "registry" you want: public, private, self-hosted, Github, Bitbucket, Gitlab, etc.
* `npm`, the client, supports installing from several canonical endpoints, including URLs. For *de facto* "registries" like Github, `npm install dstructs/matrix`, which resolves to the URL `https://github.com/dstructs/matrix`.
* In supporting canonical endpoints, you can install particular releases, etc. This is one of the reasons why when running `npm version major -m "<message>"`, the client snapshots (tags) the repo with the new version number. Hence, not only can you `npm publish`, but you can also `git push origin --tags`, and people are free to just install from the hosted repo. 

The only possible conflict when using `npm` is if two or more packages installed from various endpoints share the same name and have compatible versions. `npm` would treat these packages as the same. In this case, a content `hash` *may* be useful for distinguishing packages; however, this is not trivial. This would be better served, however, as an extension of `npm`, the client, not for creating a new package manager.

Even so, NPM supports scoped package names. In which case, you approximate a URL scheme and how, say, Golang resolves packages to `<provider>/<author>/<package>` => `@kgryte/http-server`. While name conflicts are still possible (same user name and package name on different providers), the chance of a collision is less likely.

I think you may be underestimating the advantages to a centralized registry and also have an incomplete understanding of how `npm` works and what the client is already capable of.

**Comment by mbostock** [comment]
Yes, I’m aware of these features.

In theory, npm could be used in a more decentralized manner. In practice, it is not.

The problem is more the way people commonly use package.json, and the way npm’s default behavior encourages a dependence on its central registry. I haven’t run the statistics, but I suspect if you analyzed published package.json files you’d find that 99+% of them reference packages using short names (e.g., `d3-format`) which implicitly depends on the npm centralized registry. You’d see similar usage of short names if you analyzed documentation (e.g., `npm install d3`).

A user of the npm client can avoid the central registry by creating their own registry, and some do, but you still have to deal with the vast array of published packages that declare their dependencies using short names, and it would be tedious to recreate the mapping from names to URLs yourself.

So, the point of Crom is to see if you could to move package authors away from names (and even owner/name patterns that likewise imply a centralized dependency on a particular hosting platform, if not a registry) and towards URLs. If packages declare their dependencies as URLs, and there’s likewise a simple way on the Internet to publish your package to a URL (even if it’s npm or GitHub to start), then there’s no need for a centralized registry.

The centralized registry certainly provides convenience. My hope with Crom is that we can achieve similar convenience without a similar centralized dependency by having Crom automatically expand short names into a URL. Competing against a centralized registry on usability is difficult (just like people often sacrifice security for convenience), but I hope it’s a worthwhile experiment.

I haven’t implemented the package metadata part of Crom yet (though see the [lib branch](https://github.com/mbostock/crom/tree/lib), but the idea is that rather than your package.json saying you depend on `"d3-format": "0.5"`, Crom would record a more explicit definition. You might declare a dependency on the command line as `crom install --save d3-format@0.5`, but it would be automatically expand to a definition such as this:

```json
{
  "name": "d3-format",
  "sha": "c7c1fee171767e72c496cd6ce88ab203b7e740c6aeb6eb5add59952337a6ffc8",
  "moduleUrl": "https://github.com/d3/d3-format",
  "releaseUrl": "https://github.com/d3/d3-format/releases/tag/v0.5.0",
  "version": "0.5.0",
  "range": "0.5"
}
```

So now, your package explicitly defines where your dependencies come from. You still have a local name for your convenience (`d3-format`), but there’s nothing that prevents another package from using that name to refer to something else. So there’s no longer any value in being the first in the npm registry to register a short or simple name, and packages can compete on quality rather than being first.

> I think you may be underestimating the advantages to a centralized registry and also have an incomplete understanding of how npm works and what the client is already capable of.

This was a somewhat insulting and unnecessary remark to make, but I hope I’ve made my intent more clear with the response above. :grin:
