### ISSUE TITLE
differences between Crom / Bower?

### ISSUE THREAD

**Issue by ahmadnassri** [mbostock/crom#7]
I'm a bit confused to what the difference to Bower would be in the context of relying on github for installing packages?

**Comment by mbostock** [comment]
* Bower has a centralized registry. While it stores package definitions rather than releases, and thus you don’t have to publish releases to the bower registery, it’s still a centralized registry.

* Bower doesn’t allow you to publish generated files (because its registry only stores package definitions, and packages are defined by git endpoints): all published files must be checked-in to the git repository. This is a big pain for development (e.g., [bower-chosen](https://github.com/harvesthq/bower-chosen)).

* Bower defines dependencies as names, not URLs, again because it has a centralized repository. So you have name-squatting issues, conflicts and the like.

**Comment by ahmadnassri** [comment]
so both Bower and NPM can completely bypass the registry by connecting directly to github projects, with or without `package.json` and `bower.json` definitions ... both allow dependencies to be defined as urls, also with version locking to tags / comittish

**Comment by mbostock** [comment]
Yes, you *can* use Bower and npm in a decentralized fashion, but no one does because they’re designed to favor a centralized repository. By resolving the names as URLs when you define a dependency, Crom pushes people towards a decentralized management system.

**Comment by ahmadnassri** [comment]
so in this model, github still acts as the centralized registery.

a git-only approach, would perhaps better be described as "decentralized" but with github still acting as the centralized lookup/registery it not accurate to make that claim.

**Comment by mbostock** [comment]
No. GitHub is *a* registry, but it is not the centralized registry. It so happens it’s the only registry I’ve implemented in the proof-of-concept, but you can use `Registry.register` to define any number of additional registries that are used instead of or in addition to GitHub.
